### ISSUE TITLE
localvars.md 局部变量 倒数第二句修改建议

### ISSUE THREAD

**Issue by genghisun** [BadTudou/RubyUsersGuide-zh#24]
> The box method acts something like a class, with get and set serving as methods (except those aren't really the method names, which could vary with each box instance) and contents being the lone instance variable.
box方法的作用类似于一个类，get和set作为方法(除了那些不是真正的方法名，它可能会随着每个box实例的不同而不同)，而contents是唯一的实例变量。

个人认为 *除了那些不是真正的方法名，它可能会随着每个box实例的不同而不同* 这句改成 **但是它们并不是真正的方法名，它们可能会随着每个box实例的不同而不同** 更好一些

**Comment by BadTudou** [comment]
采纳您的翻译，但是你提交修改的方式稍微有点不妥，具体修改方式如下：

1.fork https://github.com/BadTudou/RubyUsersGuide-zh到您的仓库

2.在您的仓库中对翻译进行修改

3.将修改提交至您的仓库

4.在您的仓库选择pull request，请求将修改合并至https://github.com/BadTudou/RubyUsersGuide-zh

5.在您提交pull request后，我会合并您的修改

**若有不理解的地方，请随时提出**
